### ISSUE TITLE
OAR-lib incompatible with newly release of SQLAlchemy (2.0.0)

### ISSUE THREAD

**Issue by matsKNY** [oar-team/oar3#25]
Hello all,

In the Poetry step of the installation procedure of OAR, SQLAlchemy is required with a version more recent than 1.3.0.
However, version 2.0.0 was release on the 26th of January, and OAR-lib is incompatible with the later.
As a result, without restricting the version of SQLAlchemy to be installed to a version less recent than 2.0.0, all the OAR commands fail (e.g. oarstat, oarproperty, ...).

Tests done on the latest UBI8 image with official RHEL repositories.

**Comment by matsKNY** [comment]
Associated PR with a quick and dirty workaround (to wait for the official support of SQLAlchemy 2.X.X): #26

**Comment by adfaure** [comment]
Hello, the newest release of oar uses sqlalchemy2.0.
 
Check https://github.com/oar-team/oar3/releases/tag/3.0.0.dev11

**Comment by adfaure** [comment]
Hello, the newest release of oar uses sqlalchemy2.0.
 
Check https://github.com/oar-team/oar3/releases/tag/3.0.0.dev11
