### ISSUE TITLE
Add JWT Authentication mode

### ISSUE THREAD

**Issue by vladvisan** [oar-team/oar3#34]
Based on a group conversation with @bzizou , @adfaure, @augu5te

- Produced by
  - OAR CLI
  - Any external service that has the private key associated to the public one that the OAR REST API has stored
- Verified by
    - OAR REST API
- Structure
    - iat: issued at time
    - eat: expires at time
    - oun: OAR username
- Signature
    - No CA
    - Just  a RSA public/private key pair
    - Typically [SHA-256](https://en.wikipedia.org/wiki/SHA-2#Comparison_of_SHA_functions) (input: max 2⁶⁴ bits, output: 256 bits) followed by public key encryption RSA  2048bits (modulus key size) (input: max [1960 bits](https://crypto.stackexchange.com/questions/39443/why-is-rsa-2048-max-input-245-bytes) (if PKCS#1 v1.5 padding) or [1520 bits](https://crypto.stackexchange.com/questions/42097/what-is-the-maximum-size-of-the-plaintext-message-for-rsa-oaep) (if OAEP padding for SHA-256)(recommanded) , output: 2048 bits (input and output are < key because RSA [relies on modulus (key) for both](https://math.asu.edu/sites/default/files/rsa_0.pdf) )) 
        - Recommanded combination today and for the upcoming decade in terms of anticipated calculation power increase
            - (See https://security.stackexchange.com/questions/122156/is-using-sha-256-with-rsa-2048-encryption-a-secure-certificate-hashing-algorit )
- Expiry time
    - Long (1 year+?), to simplify usage
    - Configurable
- Security
    - OAR admin can maintain a list of blacklisted people and/or tokens
        - To ban a compromised token but not the user:
            - Syntax (user, dateBan)
            - The ban date will be compared to the token's issue date
                - If the token was issued before the ban date, it is considered invalid
                - Tokens emitted after the ban date are considered valid (we suppose that the user's data-breach was one-time and patched)
        - To ban a user
            - Syntax (user, dateUnban)
            - All tokens with that user are refused while (currentDate <= dateUnban)
            - Can "permaban" a user, ex:  dateUnban="1st January 3042" 
    - "Bearer" aspect remains and is dangerous, but
        - cluster admin checks for abnormal use and can blacklist
        - optional
        - avoids extra protocol initiation steps such as [X509 Client Cert](https://comodosslstore.com/blog/what-is-ssl-tls-client-authentication-how-does-it-work.html#:~:text=of%20unauthorized%20access.-,Client%20Handshake,-In%20a%20client) and having to store an extra private key client-side
    - HTTP normally, up to the admin to put an HTTPS proxy upstream
    - For additional security, the admin can make this HTTPS proxy as complex as he wants it to, transparently for OAR REST API
        - Lots of extra security imaginable, such as fail2ban
- Use
    - HTTP Request Headers :
        - X-OAR-USER-NAME
        - X-OAR-USER-TOKEN
- Activation
    - OAR Config files
- Extension: "Proxy Authentification" mode with an "admin" JWT that can set X-OAR-USER-NAME to any user?
- Extension: Able to read private/public key not only from a file but also through external Secrets/Vaults?

**Comment by adfaure** [comment]
Hello, thanks for the summary.

This week, we had a conversation with @bzizou about the job information that one can retrieve from the api. The question is that does the API need to hide information about jobs if the requester is not the owner of the job ?

It looks like, that you need to be authenticated to get detailed information about jobs (https://github.com/oar-team/oar/blob/2.5/sources/api/oarapi.pl#L506) but no filtering is applied regarding if the user of the request owns the job. (the request just does a `SELECT * FROM jobs [...]` https://github.com/oar-team/oar/blob/2.5/sources/core/common-libs/lib/OAR/IO.pm#L2712).

But i am not an expert of oar2, maybe @npf has more insight about this ? :hook:

**Comment by vladvisan** [comment]
Interesting question, it is an arbitrary choice, maybe depending on an admin config/choice?

Also, same point could be applied to deleting someone else's job for example : https://oar.imag.fr/docs/latest/user/api.html#delete-jobs-id , no apparent checking beyond "non-public"?

Not directly related to JWT, but to authentication in general it seems.

**Comment by adfaure** [comment]
I just tested. 

If you try to kill a job that you did not issued you get this answer:
```json
{
  "id": 2,
  "cmd_output": "Deleting the job = 2 ...\n#ERROR: Cannot frag 2 ; You are not the right user. -1\n",
  "exit_status": 1
}
```

The check appends here: https://github.com/oar-team/oar3/blob/master/oar/lib/job_handling.py#L1484

**Comment by bzizou** [comment]
> Also, same point could be applied to deleting someone else's job for example : https://oar.imag.fr/docs/latest/user/api.html#delete-jobs-id , no apparent checking beyond "non-public"?

Actualy Yes. If you take a look at the perl code, for example here: https://github.com/oar-team/oar/blob/2.5/sources/api/oarapi.pl#L1070
The `$ENV{OARDO_BECOME_USER} = $authenticated_user` devolves to the next `$OARDEL_CMD` the checking of the current user, as if it was done on the command line. This command will refuse to delete a job that is not owned by `$authenticated_user`. 
To summarize: the OAR v2.5 API does not check if a user has rights or not, but transmits the username to the underlying shell commands, that will actually check that.

**Comment by bzizou** [comment]
> I just tested.
> 
> If you try to kill a job that you did not issued you get this answer:
> 
> ```json
> {
>   "id": 2,
>   "cmd_output": "Deleting the job = 2 ...\n#ERROR: Cannot frag 2 ; You are not the right user. -1\n",
>   "exit_status": 1
> }
> ```
> 
> The check appends here: https://github.com/oar-team/oar3/blob/master/oar/lib/job_handling.py#L1484

Yes. It works until the API calls the oar shell commands. But as soon as you will shortcut those commands, if you do it one day, you'll have to be careful about that and to the authorization process inside the API code.

**Comment by adfaure** [comment]
We don't call the shell commands directly, we call the python functions (hence the similar outputs).
But yes indeed, the check is not done in the "API" directly.

**Comment by bzizou** [comment]
Working now on a production cluster (on a test frontend with 4 nodes for now)!

```bash
bzizou@dahu-oar3:~$ export $(oarsub -T)
bzizou@dahu-oar3:~$ curl -X 'POST'   'https://dahu-oar3.u-ga.fr/oarapi/jobs/'   -H 'accept: application/json'   -H "Authorization: Bearer $OAR_API_TOKEN"   -H 'Content-Type: application/json'   -d '{
  "command": "sleep 3600",
  "resource": ["/cpu=1,walltime=0:10:0"],
  "project": "test",
  "type": ["devel"]
}'
{"id":88}bzizou@dahu-oar3:~$ oarstat -j 88
                                                                                     
  Job id   State     User     Duration   System message                     Queue    
 ─────────────────────────────────────────────────────────────────────────────────── 
  88       Waiting   bzizou   0:00:00    R=16,W=0:10:0,J=B,P=test,T=devel   default  
                                                                                     
bzizou@dahu-oar3:~$ 
```
