### ISSUE TITLE
oarstat job details missing "types"

### ISSUE THREAD

**Issue by bzizou** [oar-team/oar3#39]
Oarstat -fj <id> does not list the types (besteffort, etc...) of a job

Maybe a join with `job_types` is missing into BaseQueryCollection.get_jobs_for_user()

**Comment by adfaure** [comment]
Hello,

commit #69c5b3639cdb583f5afcab7489c98bebedeefaf7 fixes it, telle me if it is ok for you.
The types are returned either when jobs are printed with `oarstat -f` or if you use the rest api with the request parameters details set as true.
