### ISSUE TITLE
oarstat -sJ does not return valid JSON

### ISSUE THREAD

**Issue by GuilloteauQ** [oar-team/oar3#5]
Here is a small test using `arion` and `oar3`:

```
[root@server:/]# oarsub "sleep 150"
# INFO:  Moldable instance:  1  Estimated nb resources:  1  Walltime:  3600
OAR_JOB_ID= 2

[root@server:/]# oarstat -sj 2 -J
{
"2" : "Running",
}
```

There should not be a comma after "Running".

Looks like the issue is here:  https://github.com/oar-team/oar3/blob/b0b476f40685aac34294499e9d72c22821cd7c6a/oar/cli/oarstat.py#L245

Probably just need to change the `+ 1` in `- 1`

**Comment by adfaure** [comment]
Thank you for reporting this issue. It should be fixed with https://github.com/oar-team/oar3/commit/1367dcb191c459b77a9937b69cd1b388c5fb7351.
